version: '3'
services:
  app:
    image: edwinlll/gotask:latest 
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - DEBUG=true
    volumes:
      - /etc/hosts:/etc/hosts
      - ./.gotask.yaml:/usr/local/gotask/.gotask.yaml
    command: ["start"]
    ports:
      - 8179:8179
